spring.application.name=products
spring.data.mongodb.uri=${MONGO_DB_URL}



gemini.api.key=${GEMINI_API_KEY}

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash


spring.config.import=optional:file:.env[.properties]